name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  shu_epub:
    path: ../
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
