image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      sudo mount -t tmpfs shm -osize=4096m /dev/shm
      brew install git-flow
      dart pub get
      dart --disable-analytics
  - init: |
      flutter channel stable
      flutter upgrade
      dart pub get
  - command: dart pub get

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: ignore
    # flutter
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - dart-code.dart-code
