image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      sudo mount -t tmpfs shm -osize=4096m /dev/shm
      brew install git-flow
      flutter upgrade
      dart pub get
      dart --disable-analytics
  #- init: |
  #    dart pub get
  - command: |
      dart pub get
      eval $(command gp env -e) # Load environment variables

      WAKATIME_PATH=~/.wakatime.cfg
      rm $WAKATIME_PATH
      touch $WAKATIME_PATH
      echo -n "${WAKATIME}" | base64 --decode  > $WAKATIME_PATH

      VSCODE_SETTINGS_PATH=$HOME/.config/Code/User/settings.json
      rm $VSCODE_SETTINGS_PATH
      mkdir $HOME/.config/Code
      mkdir $HOME/.config/Code/User
      touch $VSCODE_SETTINGS_PATH
      echo -n "${VSCODE_SETTINGS}" | base64 --decode  > $VSCODE_SETTINGS_PATH

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: ignore
    # flutter
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - dart-code.dart-code
    - wakatime.vscode-wakatime
