name: shu_epub
description: A simple library for parsing ePub files
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  archive: ^3.1.11
  equatable: ^2.0.3
  xml: ^5.3.1

dev_dependencies:
  lints: ^1.0.1
  mocktail: ^0.3.0
  test: ^1.20.1
