name: shu_epub
description: A simple library for parsing ePub files
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  archive: ^3.3.1
  equatable: ^2.0.5
  meta: ^1.8.0
  xml: ">=5.3.1 <7.0.0"
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.20.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
